### ISSUE TITLE
Crash in demos/masking.js

### ISSUE THREAD

**Issue by jmgasper** [topcoderinc/pxPixi#1]
In demos/masking.js, pxscene crashes as I keep clicking to toggle the masking (sometimes one click is enough).

**Comment by conniefry** [comment]
Can we get a simple repro case for the pxscene crash you're seeing, and have you log an issue in the pxCore github repo. We need to fix the pxscene crash.  Thanks!

**Comment by jmgasper** [comment]
@conniefry - This one doesn't present in the "official" build, but the official can't currently run that demo.  This looks to be a problem in our branch code.
